mykey = "petclinic"
ami = "ami-08a0d1e16fc3f61ea"
region = "us-east-1"
instance_type = "t3a.medium"
jenkins_server_secgr = "petclinic-jenkins-server-secgr"
jenkins-server-tag = "Jenkins Server of Petclinic"
jenkins-profile = "petclinic-jenkins-profile-tr"
jenkins-role = "petclinic-jenkins-server-role"
